version: "3.8"

services:
  # Aplicação principal Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Porta da aplicação Next.js
      - "3001:3001" # Porta do JSON Server
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./db.json:/app/db.json
    networks:
      - app-network

  # Microfrontend Dashboard (exemplo)
  dashboard-microfrontend:
    build:
      context: ../dashboard-microfrontend # Ajuste para o caminho correto
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network

  # Microfrontend Transações (exemplo)
  transactions-microfrontend:
    build:
      context: ../transactions-microfrontend # Ajuste para o caminho correto
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
